title: CRUP
description: Codebase's Ramp Up Program
theme: just-the-docs

# Where the site will live
url: "https://codebase-berkeley.github.io"
baseurl: "/crup"   # VERY IMPORTANT for project repos

# Add a GitHub link in the header
aux_links:
  "View on GitHub": "https://github.com/codebase-berkeley/crup"

nav_enabled: true
color_scheme: wider

# Collections for website data
collections:
  staffers:
    sort_by: name

# Default layouts for each collection type
defaults:
  - scope:
      path: '_staffers'
      type: staffers
    values:
      layout: staffer
      height: 300
      width: 300
      subpath: '/assets/headshots/'