title: CRUP
description: A starter template using the Just the Docs theme
remote_theme: just-the-docs/just-the-docs

# Where the site will live
url: "https://codebase-berkeley.github.io"
baseurl: "/crup"   # VERY IMPORTANT for project repos

# Add a GitHub link in the header
aux_links:
  "View on GitHub": "https://github.com/codebase-berkeley/crup"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed

nav_enabled: true
color_scheme: wider