title: CRUP
description: Codebase's Ramp Up Program
theme: just-the-docs

# Where the site will live
url: "https://codebase-berkeley.github.io"
baseurl: "/crup"   # VERY IMPORTANT for project repos

# Add a GitHub link in the header
aux_links:
  "View on GitHub": "https://github.com/codebase-berkeley/crup"

nav_enabled: true
color_scheme: wider